build:
  nodes:
    coverage:
      tests:
        override:
          - command: "coverage run -m pytest"
            coverage:
              file: ".coverage"
              config_file: ".coveragerc"
              format: "py-cc"
