#!/bin/sh
# generate a license
# requires fzf

name="$(git config --global user.name)"
year="$(date "+%Y")"
license_dir="${XDG_DATA_DIR}/licenses"

download_licenses() {
	# Apache-2.0
	wget -q "https://www.apache.org/licenses/LICENSE-2.0.txt" -O "${license_dir}/Apache-2.0"
	# GPL-3.0
	wget -q "https://mit-license.org/license.txt" -O "${license_dir}/GPL-3.0"
	# MIT
	wget -q "https://mit-license.org/license.txt" -O "${license_dir}/MIT"
}

format_apache2() {
	sed -i "s/\[yyyy\]/${year}/; s/\[name of copyright owner\]/${name}/" "$1"
}

format_gpl3() {
	head -- "${license_dir}/GPL-3.0" | sed "s/(C)/(C) ${year} ${name}/" >/tmp/GPL3.tmp
	tail -n+10 -- "${license_dir}/GPL-3.0" >>/tmp/GPL3.tmp
	mv -- /tmp/GPL3.tmp "$1"
}

format_mit() {
    # FIX: name not inserting
	sed -ir "s/[0-9]{4}/${year} ${name}/" "$1"
}

pick_license() {
	if find "$license_dir" -prune -type d -empty | grep -q '^'; then
		mkdir -p -- "${license_dir}"
		download_licenses
	fi
	license="$(find "${license_dir}" -type f -printf "%f\n" | fzf +m --height=15%)"
	case "$license" in
	Apache-2.0)
		cp -f -- "${license_dir}/${license}" "${2}/LICENSE"
		format_apache2 "./LICENSE"
		;;
	GPL-3.0)
		cp -f -- "${license_dir}/${license}" "${2}/LICENSE"
		format_gpl3 "./LICENSE"
		;;
	MIT)
		cp -f -- "${license_dir}/${license}" "${2}/LICENSE"
		format_mit "./LICENSE"
		;;
	esac
}

pick_license "$@"
